<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/15 03:38:05

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'sqlite',
  'database' => 'C:\\xampp\\htdocs\\_ebeis\\sf_sandbox\\data/sandbox.db',
), 'propel');
$this->databases['propel'] = $database;
